### ISSUE TITLE
Cannot use simple vars value for setting CSS variable

### ISSUE THREAD

**Issue by winston0410** [postcss/postcss-simple-vars#109]
I tried to set simple vars as CSS variable, but it doesn't work:

```css
$blue:   #056ef0;

:root{
  --color: $blue;
}
```

It will gives an error like this:

```
Syntax Error: SyntaxError                                                      friendly-errors 20:24:33

(1:1) <css input> Unknown word

> 1 | $blue
    | ^
```

Is this by design?

**Comment by bahtou** [comment]
may be related:

Copy/Paste the example
```
$dir:    top;
$blue:   #056ef0;
$column: 200px;

.menu_link {
  background: $blue;
  width: $column;
}
.menu {
  width: calc(4 * $column);
  margin-$(dir): 10px;
}
```

I get this error:
```
(17:3) postcss-simple-vars: /path/to/styles.css Undefined variable $dir

  15 |   width: $column;
  16 |   width: calc(4 * $column);
> 17 |   margin-$(dir): 10px;
     |   ^
  18 | }
  19 |
```
Here is my `postcssrc.json`
```
module.exports = {
  "plugins": [
    "postcss-import",
    "postcss-map-get",
    "postcss-mixins",
    "postcss-hexrgba",
    "postcss-simple-vars",
    "precss",
    "postcss-preset-env",
    "autoprefixer"
  ]
};
```

**Comment by ai** [comment]
Here is my output (without any error):

```css
.menu_link {
  background: #056ef0;
  width: 200px;
}
.menu {
  width: calc(4 * 200px);
  margin-top: 10px;
}
```
