### ISSUE TITLE
cant change variables in @media query

### ISSUE THREAD

**Issue by netkudev** [postcss/postcss-simple-vars#119]
Hi, I'm trying to change $width variable in media query when the screen size is 500px, but it isn't changing.
Here's my code:
```scss
$width: 200px;

div {
  width: $width;
}

@media (min-width: 500px) {
  $width: 100px;
}
```

It's worth adding that I can change variables in other elements like this:
```scss
div {
  $width: 100px;
  width: $width;
}
```
