### ISSUE TITLE
What about arrays?

### ISSUE THREAD

**Issue by verybigman** [postcss/postcss-simple-vars#21]
Can i use vars like arrays?

``` css
$array: one, two, tree;

.btn-2 {
    color: $array[2];
}
```

**Comment by verybigman** [comment]
Maybe this possible in cssnext?)

**Comment by ai** [comment]
What is you user case for it?

I think you use PostCSS in wrong way, because in PostCSS complicated logic should be moved to JS.
PostCSS is not a Sass, where you mix your logic with styles

**Comment by verybigman** [comment]
Ok) Ex: i have button in s, m and l sizes. Every size contain 2 properties depends on size.

``` styl
$fontSize = (12 12 14 16);
$controlSize = (25 35 45 55);

for $val, $i in s, m, l, xl {
    .button_size_{$val}
    {
        font-size: ($fontSize[$i])px;
        height: ($controlSize[$i])px;
    }
}
```

I want port this to postCSS without pain:)

**Comment by ai** [comment]
You overengineering here. You have too complicated logic with bad readability. For example, you need to move eyes several time to find what font and control size will be for `m` size.

Here is a better way:

```css
@define-mixin size $name, $font, $control {
    .button_size_$(name)
    {
        font-size: $(font)px;
        height: $(control)px;
    }
}

@mixin s 12 25;
@mixin m 12 35;
@mixin l 14 45;
@mixin xl 16 55;
```
