### ISSUE TITLE
Default value with !default

### ISSUE THREAD

**Issue by RobLoach** [postcss/postcss-simple-vars#25]
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_

**Comment by ai** [comment]
I think defaault value is a mistake in Sass. In PostCSS we keep CSS simple — if you need complicated calculation, you use JS. I can’t find any user case, when default values is needed if you didn’t write complicated calculation.

**Comment by ai** [comment]
But maybe I miss something. What is your user case?

**Comment by Ser-Gen** [comment]
I have separate modules with `default` vars. On import I can redefine some or all of them:

```css

/* main.css */
$colorError: #faa;
@import 'form';

/* form.css */
$colorError: red !default;

.form--error {
	color: $colorError;
}

```

It renders to

```css
/* main.css */
.form--error {
	color: #faa;
}
```
