### ISSUE TITLE
Option to enable nested variables

### ISSUE THREAD

**Issue by jedmao** [postcss/postcss-simple-vars#27]
As I understand it, this plugin sets global vars, but what if I wanted to limit the scope of vars to the container in which they were defined and only up the stack from there? I'm imagining an option like `scoped: true` that would work like so:

```scss
.foo {
    $background: white;
    background: $background;  /* white */

    $foreground: black;
    color: $foreground;  /* black */

    &--invert {
        background-color: $foreground;  /* black */
        color: $background;  /* white */
    }
}

.bar {
    color: $foreground;  /* Error: Undefined variable $foreground */
}
```
