### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by jitendravyas** [postcss/postcss-simple-vars#28]
Input

```
$blue: #056ef0;
$column: 200px;

.menu {
    width: calc(4 * $column);
}

.menu_link {
    background: $blue;
    width: $column;
}
```

Output 
```
.menu{width:calc(4 * $column)}
.menu_link{background:#056ef0;width:200px}
```

**Comment by ai** [comment]
Can you add space between variable and `)` to test some idea?

**Comment by jitendravyas** [comment]
Do you mean space here ` width: calc(4 * $column);` ?

**Comment by ai** [comment]
`width: calc(4 * $column );`

**Comment by ai** [comment]
Can’t reproduce. I have this output:

```css
.menu {
    width: calc(4 * 200px);
}

.menu_link {
    background: #056ef0;
    width: 200px;
}
```

Maybe some other tool broke result?
