### ISSUE TITLE
string interpolation

### ISSUE THREAD

**Issue by vedam** [postcss/postcss-simple-vars#33]
hey,
I'm switching from sass to post-css and check if it's possible to transfer my sass.
With that I stumbled upon the possibility of sass-like string interpolation:
```css
$name-one: 'my-';
$name-two: 'selector-name';

.$(name-one)$(name-two) { /* declaration */}
```

was in sass:
```
.#{$name-one}#{$name-two} { /* declaration */}
```
is there a way to get this done?
btw.
first var get's interpolated

**Comment by trungtin** [comment]
And another example that currently not working:
```
$alpha-color: #111;
$beta-color: #222;
$gamma-color: #333;

@each $name in (alpha, beta, gamma){
  view-content {
    color: $($(name)-color);
  }
}
```

**Comment by ai** [comment]
@trungtin recursive interpolation will not be able until we implement Event based API https://github.com/postcss/postcss/issues/296

**Comment by ai** [comment]
@vedam your code should work. Maybe we have issue somewhere. I will try to find it today.

**Comment by ai** [comment]
@vedam everything fine. Just remove `'` from values.

Input:

```css
$name-one: my-;
$name-two: selector-name;

.$(name-one)$(name-two) { /* declaration */}
```

Output:

```css
.my-selector-name { /* declaration */}
```
