### ISSUE TITLE
!global and !default support?

### ISSUE THREAD

**Issue by RyoIkarashi** [postcss/postcss-simple-vars#54]
Does this plugin support `!global` and `!default` as SASS does support or any postCSS plugins that support these?

What I'm trying to do is to override variables, which is very useful for theming.

```css
.foo {
   $foo: 'bar' !global; 
}

$foo: 'foo' !default;

// $foo => 'bar'
```

**Comment by ai** [comment]
Nope https://github.com/postcss/postcss-simple-vars/issues/52

**Comment by ai** [comment]
Can you show me your real case. You need `!default` only because you are thinking in Sass-way. In PostCSS you have much more power, so you could find much better code design.

**Comment by RyoIkarashi** [comment]
@ai 
If I could make variables defined in local scope global, I could override them and switch themes only by changing class names. Here is the real case belowl.
Are there any better code design for theming?

index.html
```html
<html>
<head>
<link href="/assets/main.css" rel="stylesheet">
</head>
<body class="theme-A">
...
</body>
</html>
```

main.css
```
@import 'themes.css';
@import 'variables.css';
```

themes.css
```css
.theme-A {
   $bg-color: red;
   $text-color: blue;
}
.theme-B {
   $bg-color: green;
   $text-color: yellow
}
```

variables.css
```css
$bg-color: white !default;
$text-color: black !default;
```

**Comment by ai** [comment]
This code will not work in Sass.

The best way is to use CSS Custom Variables, they support it native in browser. But not all browsers support CSS Custom Variables. In PostCSS we have polyfill, but it works only for `:root` definitions, so it is useless here.

**Comment by ai** [comment]
But I have awesome idea. Let’s write a polyfill for dynamic CSS Custom Properties!

You pass this `<body>` switching classes to plugin:

```js
require('postcss-dynamic-custom-props')({ rootClasses: ['theme-A', 'theme-B'] })
```

Then plugin will find all overrides definitions like and remember a variable names:

```css
.theme-A {
   --bg-color: red;
   --text-color: blue;
}
```

Then it will find all rules, where this variables used, like:

```css
p {
   color: var(--text-color);
}
```

On final step it merge themes classes and overrides and generate this:

```css
.themeA p {
   color: blue;
}
```

Sorry, maybe my description is little confused. Please ask me any question about it.

What do you think about this idea? Do you have time for it? (I will help you step-by-step)
