### ISSUE TITLE
Reset value using webpack?

### ISSUE THREAD

**Issue by alansouzati** [postcss/postcss-simple-vars#57]
I have the following css using simple vars:

```css
$brandColor: #8C50FF;

.common {
  color: $brandColor;
  text-decoration: none;
}
```

Now I want to replace the brandColor value in my webpack config, based on the docs I tried:

```javascript
   vars({
		variables: {
			brandColor: '#3e00b6'
		}
    })
```

The actual value remains `#8C50FF`. If I remove the `$brandColor: #8C50FF;` entry, then the value is set.

It would be great to not require the variables to be present always and set a default one instead.
