### ISSUE TITLE
Is there a way to ignore dollar signs in certain places?

### ISSUE THREAD

**Issue by cullylarson** [postcss/postcss-simple-vars#86]
I'm using `postcss` with `styled-jsx`. `postcss` processes the style and sends it to styled-jsx to embed in the page. `styled-jsx` allows using javascript variables in styles. The problem is that variables in JS string templates use dollar signs and `postcss-simple-vars` will try to interpret them before sending to `styled-jsx`. Since the variable doesn't exist as far as `postcss-simple-vars` is concerned, it produces an empty value.

For example, if `postcss-simple-vars` gets this:

```css
<style jsx>
    {`
        .categories {
            --numColumns: ${numColumns.xl};
            --gapWidth: 20px;

            padding-left: 10px;
            overflow-x: hidden;
        }
    }`
</style>
```

It will produce something like:

```css
.categories {
    --numColumns: ;
    --gapWidth: 20px;

    padding-left: 10px;
    overflow-x: hidden;
}
```

I'm wondering if there's a way to tell `postcss-simple-vars` to ignore a line or a string.
